project_id = "tyasymsyqlsjilhwezvy"

[functions.ai-market-analysis]
verify_jwt = false

[functions.ai-chart-analysis]
verify_jwt = false

[functions.whop-webhook]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false

[functions.chart-analyzer]
verify_jwt = false

[functions.charted-chat]
verify_jwt = false